# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'example.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 40, 61, 51))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 31))
        self.label.setObjectName("label")
        #self.pushButton_2 = FF(self.centralwidget,"push")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(870, 50, 61, 51))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 130, 61, 61))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(430, 140, 61, 51))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(710, 190, 61, 51))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(980, 190, 61, 51))
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 330, 61, 51))
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(300, 250, 61, 51))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(500, 270, 61, 51))
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(820, 300, 61, 61))
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(120, 480, 61, 51))
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(350, 410, 61, 51))
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 510, 661, 61))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 20, 61, 51))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(620, 470, 61, 51))
        self.pushButton_14.setStyleSheet("")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(960, 430, 61, 51))
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 500, 81, 51))
        self.pushButton_16.setObjectName("pushButton_16")
        self.image_1 = QtWidgets.QLabel(self.centralwidget)
        self.image_1.setGeometry(QtCore.QRect(230, 0, 101, 101))
        self.image_1.setText("")
        self.image_1.setObjectName("image_1")
        self.image_4 = QtWidgets.QLabel(self.centralwidget)
        self.image_4.setGeometry(QtCore.QRect(40, 110, 101, 101))
        self.image_4.setText("")
        self.image_4.setObjectName("image_4")
        self.image_8 = QtWidgets.QLabel(self.centralwidget)
        self.image_8.setGeometry(QtCore.QRect(40, 300, 101, 101))
        self.image_8.setText("")
        self.image_8.setObjectName("image_8")
        self.image_12 = QtWidgets.QLabel(self.centralwidget)
        self.image_12.setGeometry(QtCore.QRect(140, 450, 101, 101))
        self.image_12.setText("")
        self.image_12.setObjectName("image_12")
        self.image_13 = QtWidgets.QLabel(self.centralwidget)
        self.image_13.setGeometry(QtCore.QRect(360, 380, 101, 101))
        self.image_13.setText("")
        self.image_13.setObjectName("image_13")
        self.image_9 = QtWidgets.QLabel(self.centralwidget)
        self.image_9.setGeometry(QtCore.QRect(320, 230, 101, 101))
        self.image_9.setText("")
        self.image_9.setObjectName("image_9")
        self.image_14 = QtWidgets.QLabel(self.centralwidget)
        self.image_14.setGeometry(QtCore.QRect(560, 430, 101, 101))
        self.image_14.setText("")
        self.image_14.setObjectName("image_14")
        self.image_10 = QtWidgets.QLabel(self.centralwidget)
        self.image_10.setGeometry(QtCore.QRect(510, 240, 101, 101))
        self.image_10.setText("")
        self.image_10.setObjectName("image_10")
        self.image_5 = QtWidgets.QLabel(self.centralwidget)
        self.image_5.setGeometry(QtCore.QRect(450, 100, 101, 101))
        self.image_5.setText("")
        self.image_5.setObjectName("image_5")
        self.image_15 = QtWidgets.QLabel(self.centralwidget)
        self.image_15.setGeometry(QtCore.QRect(890, 420, 101, 101))
        self.image_15.setText("")
        self.image_15.setObjectName("image_15")
        self.image_11 = QtWidgets.QLabel(self.centralwidget)
        self.image_11.setGeometry(QtCore.QRect(750, 300, 101, 101))
        self.image_11.setText("")
        self.image_11.setObjectName("image_11")
        self.image_7 = QtWidgets.QLabel(self.centralwidget)
        self.image_7.setGeometry(QtCore.QRect(910, 170, 101, 101))
        self.image_7.setText("")
        self.image_7.setObjectName("image_7")
        self.image_3 = QtWidgets.QLabel(self.centralwidget)
        self.image_3.setGeometry(QtCore.QRect(810, 20, 101, 101))
        self.image_3.setText("")
        self.image_3.setObjectName("image_3")
        self.image_6 = QtWidgets.QLabel(self.centralwidget)
        self.image_6.setGeometry(QtCore.QRect(650, 160, 101, 101))
        self.image_6.setText("")
        self.image_6.setObjectName("image_6")
        self.image_2 = QtWidgets.QLabel(self.centralwidget)
        self.image_2.setGeometry(QtCore.QRect(560, 0, 101, 101))
        self.image_2.setText("")
        self.image_2.setObjectName("image_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1051, 541))
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_16.raise_()
        self.image_1.raise_()
        self.pushButton.raise_()
        self.image_4.raise_()
        self.image_8.raise_()
        self.image_12.raise_()
        self.image_13.raise_()
        self.image_9.raise_()
        self.image_14.raise_()
        self.image_10.raise_()
        self.image_5.raise_()
        self.image_15.raise_()
        self.image_11.raise_()
        self.image_7.raise_()
        self.image_3.raise_()
        self.image_6.raise_()
        self.image_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_8.raise_()
        self.pushButton_12.raise_()
        self.pushButton_9.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.pushButton_10.raise_()
        self.pushButton_5.raise_()
        self.pushButton_2.raise_()
        self.pushButton_6.raise_()
        self.pushButton_3.raise_()
        self.pushButton_7.raise_()
        self.pushButton_11.raise_()
        self.pushButton_15.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "t: 0"))
        self.label_2.setText(_translate("MainWindow", "choose vertices to save"))
        self.pushButton_16.setText(_translate("MainWindow", "t++"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

